### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by bsima** [cies/htoml#4]
The latest version of TOML [is now 4.0](https://github.com/mojombo/toml/blob/master/versions/en/toml-v0.4.0.md), not 3.1 as the README states.

**Comment by voidzero** [comment]
To adding to this - the README contains the following line:

```let r = parseTomlDoc "" txt```

Which leads to the following error:
```<interactive>:6:25:
    Couldn't match type ‘[Char]’ with ‘Data.Text.Internal.Text’
    Expected type: Data.Text.Internal.Text
      Actual type: String
    In the second argument of ‘parseTomlDoc’, namely ‘txt’
    In the expression: parseTomlDoc "" txt
```

**Comment by cies** [comment]
@voidzero It seems your REPL is not picking up the `.ghci` file. I've stackified the instructions in the README, maybe you can have another look.

**Comment by cies** [comment]
@bsima I'll pull in some PRs that will fix this, in the meanwhile I'll close this issue.
